# Generated by Django 5.2.6 on 2025-09-06 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_phone_customer_mobile_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='store.customer'),
        ),
    ]
