# Generated by Django 5.2.6 on 2025-09-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_customer_address_remove_customer_cust_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
    ]
